### ISSUE TITLE
Anything involving a name fails

### ISSUE THREAD

**Issue by go2tom42** [kemalyazici/shortcode-imdb#2]
Wordpress 6.1.1
IMDB SHORTCODE 6.0.8

I've tried
```
[imdb]nm0001659[/imdb]
[imdb_name]nm0001659[/imdb_name]
[imdb data="detailed"]nm0001659[/imdb]
[imdb style="transparent"]nm0000489[/imdb]
```
Wordpress result "There has been a critical error on this website."

Log show these errors
`[Thu Jan 26 04:08:55.607178 2023] [php:warn] [pid 106580] [client 172.18.0.47:34936] PHP Warning:  Attempt to read property "nodeValue" on null in /var/www/html/wp-content/plugins/shortcode-imdb/includes/classes/class.imdb.php on line 220, referer: https://blog.xxxx.pw/wp-admin/post.php?post=1&action=edit`

`[Thu Jan 26 04:08:55.608472 2023] [php:error] [pid 106580] [client 172.18.0.47:34936] PHP Fatal error:  Uncaught Error: Call to a member function getAttribute() on null in /var/www/html/wp-content/plugins/shortcode-imdb/includes/classes/class.imdb.php:248\nStack trace:\n#0 /var/www/html/wp-content/plugins/shortcode-imdb/includes/classes/class.imdb.php(981): shimdb_imdb_grab->name('nm0000489')\n#1 /var/www/html/wp-content/plugins/shortcode-imdb/includes/helpers/shortcodes.php(21): shimdb_imdb_grab->grab_imdb('nm0000489', 'name')\n#2 /var/www/html/wp-content/plugins/shortcode-imdb/includes/helpers/shortcodes.php(32): shimdb_imdb_name_shortcode(Array, 'nm0000489')\n#3 /var/www/html/wp-includes/shortcodes.php(355): shimdb_imdb_general_shordcode(Array, 'nm0000489', 'imdb')\n#4 [internal function]: do_shortcode_tag(Array)\n#5 /var/www/html/wp-includes/shortcodes.php(227): preg_replace_callback('/\\\\[(\\\\[?)(imdb)(...', 'do_shortcode_ta...', '\\n<div class="is...')\n#6 /var/www/html/wp-includes/class-wp-hook.php(308): do_shortcode('\\n<div class="is...')\n#7 /var/www/html/wp-includes/plugin.php(205): WP_Hook->apply_filters('\\n<div class="is...', Array)\n#8 /var/www/html/wp-includes/rest-api/endpoints/class-wp-rest-revisions-controller.php(607): apply_filters('the_content', '<!-- wp:group {...')\n#9 /var/www/html/wp-includes/rest-api/endpoints/class-wp-rest-autosaves-controller.php(416): WP_REST_Revisions_Controller->prepare_item_for_response(Object(WP_Post), Object(WP_REST_Request))\n#10 /var/www/html/wp-includes/rest-api/endpoints/class-wp-rest-autosaves-controller.php(247): WP_REST_Autosaves_Controller->prepare_item_for_response(Object(WP_Post), Object(WP_REST_Request))\n#11 /var/www/html/wp-includes/rest-api/class-wp-rest-server.php(1171): WP_REST_Autosaves_Controller->create_item(Object(WP_REST_Request))\n#12 /var/www/html/wp-includes/rest-api/class-wp-rest-server.php(1018): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/wp/v2/posts/(?...', Array, NULL)\n#13 /var/www/html/wp-includes/rest-api/class-wp-rest-server.php(442): WP_REST_Server->dispatch(Object(WP_REST_Request))\n#14 /var/www/html/wp-includes/rest-api.php(410): WP_REST_Server->serve_request('/wp/v2/posts/1/...')\n#15 /var/www/html/wp-includes/class-wp-hook.php(308): rest_api_loaded(Object(WP))\n#16 /var/www/html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)\n#17 /var/www/html/wp-includes/plugin.php(565): WP_Hook->do_action(Array)\n#18 /var/www/html/wp-includes/class-wp.php(399): do_action_ref_array('parse_request', Array)\n#19 /var/www/html/wp-includes/class-wp.php(780): WP->parse_request('')\n#20 /var/www/html/wp-includes/functions.php(1332): WP->main('')\n#21 /var/www/html/wp-blog-header.php(16): wp()\n#22 /var/www/html/index.php(17): require('/var/www/html/w...')\n#23 {main}\n  thrown in /var/www/html/wp-content/plugins/shortcode-imdb/includes/classes/class.imdb.php on line 248, referer: https://blog.XXXXX.pw/wp-admin/post.php?post=1&action=edit`

**Comment by kemalyazici** [comment]
There is a big update on the road.

**Comment by go2tom42** [comment]
How long is this road?

**Comment by kemalyazici** [comment]
Very close...
